# Generated by Django 4.2.6 on 2023-10-13 09:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлено')),
                ('image', models.ImageField(upload_to='post_images', verbose_name='Фото')),
                ('link', models.CharField(max_length=256, verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'работа',
                'verbose_name_plural': 'Работы',
                'default_related_name': 'works',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.CharField(max_length=50, verbose_name='Должность')),
                ('bio', models.TextField(max_length=1000, verbose_name='Био')),
                ('techs', models.TextField(max_length=100, verbose_name='Технологии')),
                ('location', models.CharField(max_length=30, verbose_name='Местоположение')),
                ('birth_date', models.DateField(null=True, verbose_name='Дата рождения')),
                ('avatar', models.ImageField(upload_to='avatars', verbose_name='Аватар')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'профиль',
                'verbose_name_plural': 'Профили',
                'default_related_name': 'profiles',
            },
        ),
    ]
